[project]
name = "day09"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=8.31.0",
    "nbformat>=5.10.4",
]
